{{- if .Values.aws.secret.create -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app: {{ template "aws-ec2-tagger.name" . }}
    chart: {{ .Chart.Name}}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: aws-ec2-tagger-iam-credentials
data:
  AWS_ACCESS_KEY_ID: {{ required "An AWS IAM access key must be supplied" .Values.aws.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ required "An AWS IAM access secret must be supplied" .Values.aws.accessSecret | b64enc }}
{{- end -}}
