{{- if .Values.aws.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "aws-ec2-tagger.name" . }}
    chart: {{ .Chart.Name}}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: aws-ec2-tagger-iam-credentials
type: Opaque
data:
  awsAccessKey: {{ required "An AWS IAM access key must be supplied" .Values.aws.accessKey | quote }}
  awsAccessSecret: {{ required "An AWS IAM access secret must be supplied" .Values.aws.accessSecret | quote }}
{{- end -}}
